# Tela
LARGURA = 1200
ALTURA = 600

# Personagem
PERSONAGEM_X = 150
PERSONAGEM_Y = 350
PERSONAGEM_LARGURA = 85
PERSONAGEM_ALTURA = 120
PERSONAGEM_LARGURA_AGACHADO = 90
PERSONAGEM_ALTURA_AGACHADO = 90

# Margens de hitbox (ajuste fino de colisão)
PERSONAGEM_HITBOX_MARGEM_X = 10
PERSONAGEM_HITBOX_MARGEM_Y = 5

ALIEN1_HITBOX_MARGEM = 8
ALIEN2_HITBOX_MARGEM = 10
ALIEN3_HITBOX_MARGEM = 10
OVNI_HITBOX_MARGEM = 10

# Física
GRAVIDADE = 0.8
FORCA_PULO = -16
CHAO = 400

# Animação
VELOCIDADE_ANIMACAO = 8

# Fundo
VELOCIDADE_FUNDO = 3

# Aliens (obstáculos de pulo)
ALIEN_VELOCIDADE = 6
VELOCIDADE_ANIMACAO_ALIEN = 10

ALIEN1_LARGURA = 60
ALIEN1_ALTURA = 60

ALIEN2_LARGURA = 90
ALIEN2_ALTURA = 90

OVNI_LARGURA = 120
OVNI_ALTURA = 60
OVNI_Y = CHAO - 30

# Spawn de obstáculos (intervalo em frames)
INTERVALO_MIN_OBSTACULO = 60
INTERVALO_MAX_OBSTACULO = 150

# Pontuação
VELOCIDADE_PONTUACAO = 5
FONTE_TAMANHO = 36
COR_PONTUACAO = (255, 255, 255)
MARGEM_PONTUACAO = 20

# Nave
NAVE_LARGURA = 800
NAVE_ALTURA = 500
